- hosts: machines
  vars:
    wordpress_database_name: "sacred_Arda"
    wordpress_database_user: "mighty_Manwe"
    wordpress_database_password: "children_of_Iluvatar"
  roles:
    - {role: geerlingguy.php, tags: ["php"]}
    - {role: geerlingguy.mysql, tags: ["mysql"]}
    - {role: geerlingguy.php-mysql, tags: ["php", "mysql"]}
    - {role: geerlingguy.apache, tags: ["apache"]}
    - {role: wordpress, tags: ["wordpress"]}
  become: yes
  become_user: root

- hosts: machines
  roles:
    - {role: other, tags: ["other"]}
