---
- name: Download WordPress
  copy:
    src=./files/latest.tar.gz
    dest=/tmp/latest.tar.gz

- name: Extract WordPress
  unarchive:
    src=/tmp/latest.tar.gz
    dest=/var/www/
    copy=no

- name: Copy database dump file
  copy:
    src=dump.sql
    dest=/tmp

- name: Restore database
  mysql_db:
    name: my_db
    state: import
    target: /tmp/dump.sql

- name: Create MYSQL user
  mysql_user:
    name={{wordpress_database_user}}
    password={{wordpress_database_password}}
    priv=*.*:ALL
    state=present

- name: Update default Apache site
  template:
    src=wordpress.conf
    dest=/etc/apache2/sites-enabled/000-default.conf

- name: Create directory for sertificates
  file:
    path=/etc/apache2/ssl
    state=directory
    mode=0755

- name: Copy self signed sertificate
  copy:
    src="{{item}}"
    dest="/etc/apache2/ssl/{{item}}"
  with_items:
    - apache.crt
    - apache.key

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/wordpress/

- name: Create directory for core files
  file:
    path=/var/www/wordpress/cores
    state=directory
    owner=www-data
    group=www-data
    mode=0755

- name: Add CoreDumps folder
  lineinfile:
    dest=/etc/apache2/apache2.conf
    line="CoreDumpDirectory /var/www/wordpress/cores"

# - name: Restart Apache
  # service:
    # name=apache2
    # state=restarted
